<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

  <template id="loginFormTemplate">
    <div id ="hideLoginForm">
      <h2>Logga in användare</h2>
      <form id="loginForm">
        <input type="text" name="username" id="username" placeholder="Username">
        <input type="password" name="password" id="password" placeholder="Password">
        <input type="submit" value="Logga in">
      </form>
    </div>
  </template>

  <template id="registerFormTemplate">
    <div id ="hideRegisterForm">
      <h2>Registrera användare</h2>
      <form id="registerForm">
        <input type="text" name="username" id="username" placeholder="Username">
        <input type="password" name="password" id="password" placeholder="Password">
        <input type="submit" value="Register">
      </form>
    </div>
  </template>

  <template id="createEntryFormTemplate">
     <div id ="hideEntryForm">
     <form id="entriesForm">
       <input type="text" name="title" id="title">
       <textarea name="content" id="content" cols="30" rows="10"></textarea>
       <input type="submit" value="Add">
     </form>

  </template>

  <template id="createCommentFormTemplate">

     <form id="commentForm">
     <br>
       <textarea name="content" id="content" cols="30" rows="10" placeholder="Comment...."></textarea>
       <input type="submit" value="Add comment">
     </form>

  </template>

  <div class="container">

    <header>
      <h1><?=$title?></h1>
    </header>

    <main>

    </main>

  </div>

  <script type="text/javascript" src="main.js"></script>

</body>
</html>
